### ISSUE TITLE
pg can give error on bundle install

### ISSUE THREAD

**Issue by mystycs** [learn-co-students/rails-programmer-profile-partials-v-000#89]
Might get this error during bundle install

`Building native extensions.  This could take a while...
ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.`

If you get it, run `sudo apt-get install libpq-dev
` and run bundle install again.

**Comment by gj** [comment]
Fixed in https://github.com/learn-co-curriculum/rails-programmer-profile-partials/commit/19df034f2804b2487ab73a3378b610276e3cea2f.

Thanks @mystycs !
